### ISSUE TITLE
Cant add server in admin menu

### ISSUE THREAD

**Issue by Slitzo3** [nikooo777/hlstatsx-community-edition#4]
I cant see any errors on the page when i try to add a server in the admin panel. So i am wondering if this is a this a known bug or does anyone know a fix to this?

**Comment by benjamin966** [comment]
Hallo, Fix HLstatsX PHP7 Download : www.Revolution-Fighters.de 

have fun :)

**Comment by nikooo777** [comment]
you guys need to refer to the sourcemod forum for support. this release by me is just a mirror because there wasn't one on github. I'm not maintaining it
